---
- name: First Playbook which will install latest version of Apache httpd
  hosts: all
  tasks:
    - name: Install the latest version of Apache
      ansible.builtin.yum:
        name: httpd
        state: latest
    - name: Start the httpd service, if not started
      ansible.builtin.service:                         
        name: httpd                                
        state: started
        enabled: yes
...
